require('dotenv').config();
const { sequelize, Course } = require('./src/models');

const courses = [
  { title: 'DSA Full Course - Striver', description: 'Complete DSA from scratch with Striver. Arrays, Trees, Graphs, DP and more.', category: 'Data Structures & Algorithms', price: 499, original_price: 1999, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/0bHoB32fuj0/maxresdefault.jpg', youtube_playlist_id: 'PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz', total_hours: 40, total_lessons: 150, instructor: 'Striver' },
  { title: 'DSA with Java - Kunal Kushwaha', description: 'DSA complete course in Java for beginners to advanced.', category: 'Data Structures & Algorithms', price: 399, original_price: 1499, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/VTLCoHnyACE/maxresdefault.jpg', youtube_playlist_id: 'PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt', total_hours: 35, total_lessons: 120, instructor: 'Kunal Kushwaha' },
  { title: 'DSA in C++ - CodeHelp', description: 'Data Structures and Algorithms in C++ by Love Babbar.', category: 'Data Structures & Algorithms', price: 599, original_price: 1999, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/WQoB2z67hvY/maxresdefault.jpg', youtube_playlist_id: 'PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA', total_hours: 45, total_lessons: 160, instructor: 'Love Babbar' },
  { title: 'DSA - Apna College', description: 'DSA full course in Java by Apna College.', category: 'Data Structures & Algorithms', price: 349, original_price: 1499, rating: 4.9, thumbnail_url: 'https://img.youtube.com/vi/AT14lCXuMKI/maxresdefault.jpg', youtube_playlist_id: 'PLdo5W4Nhv31bbKJzrsKfMpo_grxuLl8LU', total_hours: 38, total_lessons: 140, instructor: 'Apna College' },
  { title: 'DSA - Pepcoding', description: 'Complete DSA course by Pepcoding for placements.', category: 'Data Structures & Algorithms', price: 399, original_price: 1799, rating: 4.6, thumbnail_url: 'https://img.youtube.com/vi/rZ41y93P2Qo/maxresdefault.jpg', youtube_playlist_id: 'PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ', total_hours: 30, total_lessons: 110, instructor: 'Pepcoding' },
  { title: 'OS Full Course - CodeHelp', description: 'Operating Systems complete course by Love Babbar.', category: 'Operating Systems', price: 299, original_price: 1499, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/_TpOHMCODXo/maxresdefault.jpg', youtube_playlist_id: 'PLDzeHZWIZsTr3nwuTegHLa2qlI81QweYG', total_hours: 22, total_lessons: 80, instructor: 'Love Babbar' },
  { title: 'OS - Gate Smashers', description: 'Operating Systems for GATE and university exams.', category: 'Operating Systems', price: 249, original_price: 999, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/bkSWJJZNgf8/maxresdefault.jpg', youtube_playlist_id: 'PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p', total_hours: 20, total_lessons: 75, instructor: 'Gate Smashers' },
  { title: 'OS - Neso Academy', description: 'Complete Operating Systems course by Neso Academy.', category: 'Operating Systems', price: 349, original_price: 1299, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/vBURTt97EkA/maxresdefault.jpg', youtube_playlist_id: 'PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O', total_hours: 25, total_lessons: 90, instructor: 'Neso Academy' },
  { title: 'OS - Jenny Lectures', description: 'Operating Systems lectures for B.Tech students.', category: 'Operating Systems', price: 199, original_price: 999, rating: 4.6, thumbnail_url: 'https://img.youtube.com/vi/By6lWjiPpVI/maxresdefault.jpg', youtube_playlist_id: 'PLG9aCp4uE-s17rFjWM8KchGlffXgOzzVP', total_hours: 18, total_lessons: 65, instructor: 'Jenny Lectures' },
  { title: 'DBMS Full Course - CodeHelp', description: 'Database Management Systems complete course.', category: 'Database Management Systems', price: 299, original_price: 1499, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/eYpXCdvKwEQ/maxresdefault.jpg', youtube_playlist_id: 'PLDzeHZWIZsTpukecmA2p5rhHM14bl2dHU', total_hours: 20, total_lessons: 70, instructor: 'Love Babbar' },
  { title: 'DBMS - Gate Smashers', description: 'DBMS for GATE preparation with all concepts.', category: 'Database Management Systems', price: 249, original_price: 999, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/kBdlM6hNDAE/maxresdefault.jpg', youtube_playlist_id: 'PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y', total_hours: 18, total_lessons: 65, instructor: 'Gate Smashers' },
  { title: 'DBMS - Apna College', description: 'Complete DBMS course by Apna College.', category: 'Database Management Systems', price: 349, original_price: 1299, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/T7AxM7Vqvaw/maxresdefault.jpg', youtube_playlist_id: 'PLdo5W4Nhv31b33kF46f9aFjoJPOkdlsRc', total_hours: 22, total_lessons: 80, instructor: 'Apna College' },
  { title: 'DBMS - Jenny Lectures', description: 'DBMS full course for university and competitive exams.', category: 'Database Management Systems', price: 199, original_price: 999, rating: 4.6, thumbnail_url: 'https://img.youtube.com/vi/khKoJUpcXUE/maxresdefault.jpg', youtube_playlist_id: 'PLG9aCp4uE-s0bu-I8fgDXXhVLO4qVROGy', total_hours: 16, total_lessons: 60, instructor: 'Jenny Lectures' },
  { title: 'DBMS - Sanchit Jain', description: 'DBMS complete course with SQL and normalization.', category: 'Database Management Systems', price: 279, original_price: 1199, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/YRnjGeQbsHQ/maxresdefault.jpg', youtube_playlist_id: 'PLmXKhU9FNesR1rSES7oLdJaNFgmuj0SYV', total_hours: 19, total_lessons: 68, instructor: 'Sanchit Jain' },
  { title: 'CN Full Course - Gate Smashers', description: 'Computer Networks complete course for GATE.', category: 'Computer Networks', price: 299, original_price: 1299, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/JFF2vJaN0Cw/maxresdefault.jpg', youtube_playlist_id: 'PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_', total_hours: 24, total_lessons: 85, instructor: 'Gate Smashers' },
  { title: 'CN - Neso Academy', description: 'Computer Networks full course by Neso Academy.', category: 'Computer Networks', price: 349, original_price: 1299, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/VwN91x5i25g/maxresdefault.jpg', youtube_playlist_id: 'PLBlnK6fEyqRgMCUAG0XRw78UA8qnv6jEx', total_hours: 26, total_lessons: 90, instructor: 'Neso Academy' },
  { title: 'CN - Sanchit Jain', description: 'Computer Networks for GATE and university exams.', category: 'Computer Networks', price: 249, original_price: 999, rating: 4.6, thumbnail_url: 'https://img.youtube.com/vi/q3Z3Qa1UNBA/maxresdefault.jpg', youtube_playlist_id: 'PLmXKhU9FNesSjFbXSZGF8JF_4LVwwofCd', total_hours: 20, total_lessons: 72, instructor: 'Sanchit Jain' },
  { title: 'CN - Ravindrababu Ravula', description: 'Computer Networks GATE lectures.', category: 'Computer Networks', price: 199, original_price: 999, rating: 4.5, thumbnail_url: 'https://img.youtube.com/vi/RY32wSQDekE/maxresdefault.jpg', youtube_playlist_id: 'PLEbnTDJUr_IegfoqO4iPnPYQki7ymqoTn', total_hours: 15, total_lessons: 55, instructor: 'Ravindrababu Ravula' },
  { title: 'CN - Shiksha Online', description: 'Computer Networks complete video series.', category: 'Computer Networks', price: 149, original_price: 799, rating: 4.4, thumbnail_url: 'https://img.youtube.com/vi/3SbtNuK5YZ8/maxresdefault.jpg', youtube_playlist_id: 'PLOG_8OlGMp73hMyn-WX1M2Q4ON98DmaRq', total_hours: 14, total_lessons: 50, instructor: 'Shiksha Online' },
  { title: 'ML Full Course - CampusX', description: 'Machine Learning complete course in Hindi.', category: 'Machine Learning', price: 599, original_price: 1999, rating: 4.9, thumbnail_url: 'https://img.youtube.com/vi/1L420xXpDTg/maxresdefault.jpg', youtube_playlist_id: 'PLaldQ9PzZd9qT0KsKJ7yCq70iFFP3MFJ5', total_hours: 50, total_lessons: 180, instructor: 'CampusX' },
  { title: 'ML - Krish Naik', description: 'Machine Learning A-Z with Python by Krish Naik.', category: 'Machine Learning', price: 499, original_price: 1799, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/i_LwzRVP7bg/maxresdefault.jpg', youtube_playlist_id: 'PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe', total_hours: 35, total_lessons: 130, instructor: 'Krish Naik' },
  { title: 'ML - Stanford Andrew Ng', description: 'The legendary Stanford ML course by Andrew Ng.', category: 'Machine Learning', price: 799, original_price: 2999, rating: 4.9, thumbnail_url: 'https://img.youtube.com/vi/jGwO_UgTS7I/maxresdefault.jpg', youtube_playlist_id: 'PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU', total_hours: 60, total_lessons: 200, instructor: 'Andrew Ng' },
  { title: 'ML - Siddhardhan', description: 'Machine Learning projects and concepts in Python.', category: 'Machine Learning', price: 399, original_price: 1499, rating: 4.7, thumbnail_url: 'https://img.youtube.com/vi/D1eL1EnxXXQ/maxresdefault.jpg', youtube_playlist_id: 'PLfFghEul0VqT6RCNaHFkiuMFJFMBnMFAp', total_hours: 28, total_lessons: 95, instructor: 'Siddhardhan' },
  { title: 'ML - Codebasics', description: 'Machine Learning tutorial series for beginners.', category: 'Machine Learning', price: 449, original_price: 1299, rating: 4.8, thumbnail_url: 'https://img.youtube.com/vi/yfIJDmjh0uA/maxresdefault.jpg', youtube_playlist_id: 'PLTukPelH6ee59Kt9WLEcR5Yea9uFZTuiO', total_hours: 32, total_lessons: 115, instructor: 'Codebasics' },
];

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to DB');
    await Course.destroy({ where: {} });
    console.log('Cleared existing courses');
    await Course.bulkCreate(courses);
    console.log('Seeded', courses.length, 'courses successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
